# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sqlite
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=sqlite' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_LARGEFILE_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DSQLITE_THREADSAFE=1' \
	'-DSQLITE_DEFAULT_MEMSTATUS=0' \
	'-DSQLITE_OMIT_LOAD_EXTENSION' \
	'-DSQLITE_OMIT_DEPRECATED' \
	'-DBUILDING_NODE_EXTENSION' \
	'-DDEBUG' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug := \
	-O3

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-fno-strict-aliasing \
	-std=gnu++17 \
	-O3

INCS_Debug := \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/include/node \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/src \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/openssl/config \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/openssl/openssl/include \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/uv/include \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/zlib \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/v8/include \
	-I/home/kobrarocks/Git/b2p-website/libs/sqlite/src/third_party/sqlite

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=sqlite' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_LARGEFILE_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DSQLITE_THREADSAFE=1' \
	'-DSQLITE_DEFAULT_MEMSTATUS=0' \
	'-DSQLITE_OMIT_LOAD_EXTENSION' \
	'-DSQLITE_OMIT_DEPRECATED' \
	'-DBUILDING_NODE_EXTENSION'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release := \
	-O3

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-fno-strict-aliasing \
	-std=gnu++17 \
	-O3

INCS_Release := \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/include/node \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/src \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/openssl/config \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/openssl/openssl/include \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/uv/include \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/zlib \
	-I/home/kobrarocks/.cache/node-gyp/22.19.0/deps/v8/include \
	-I/home/kobrarocks/Git/b2p-website/libs/sqlite/src/third_party/sqlite

OBJS := \
	$(obj).target/$(TARGET)/src/native/sqlite_addon.o \
	$(obj).target/$(TARGET)/src/third_party/sqlite/sqlite3.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64

LIBS :=

$(obj).target/sqlite.node: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/sqlite.node: LIBS := $(LIBS)
$(obj).target/sqlite.node: TOOLSET := $(TOOLSET)
$(obj).target/sqlite.node: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/sqlite.node
# Add target alias
.PHONY: sqlite
sqlite: $(builddir)/sqlite.node

# Copy this to the executable output path.
$(builddir)/sqlite.node: TOOLSET := $(TOOLSET)
$(builddir)/sqlite.node: $(obj).target/sqlite.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/sqlite.node
# Short alias for building this executable.
.PHONY: sqlite.node
sqlite.node: $(obj).target/sqlite.node $(builddir)/sqlite.node

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/sqlite.node

